[package]
name = "amsterword"
version = "1.0.0"
edition = "2021"

[dependencies]
rand        =   {version = "0.8.*"}
serde       =   {version = "1.0.*", features = ["derive"]}
serde_json  =   {version = "1.0.*"}
crossterm   =   {version = "0.27.*"}